#! /usr/bin/perl -w

###############
##   Title   ##
###############################################################################

my $header = <<'EOHEADER';
------------------------------------------------------------------------------
		                  sepPDB		      
------------------------------------------------------------------------------					      

 A script to split TER separated multi PDB files into single PDB files.  Will
 return the number of structures found.
 									      
		     Authors: (C) Marc Offman				      
			       Date: 05.03.2012 			      
			       Version: 1				      
									      
									      
			  Thank you for using sepPDB!			      
	    Any questions should be adressed to offman@rostlab.org	      
									      
------------------------------------------------------------------------------

EOHEADER


$cLine ="USAGE: seqPDB <IN FILE>\n";

if (not defined $ARGV[0]) {
        print $cLine;
        exit(1);
}

$rw = open(IN,$ARGV[0]);               #open sourcefile
if(not defined($rw)) {  #check file
	die "could not open file: $ARGV[0]\n";
}

$i=0;
$cnt=0;
$afl = 0;
$name=$ARGV[0];
$name=~s/\..*//;
$oldRes = -9999;
$oldChain = "#";
$last = NULL;
while(<IN>){
	if(/^TER/ && $last !~m/^TER/ && $afl > 0){
		$cnt++;
		$last = "TER";
	}
	elsif(/^ATOM/){
		$resNr = substr($_,22,4);
		$chain = substr($_,21,1);
		if(($oldRes > $resNr && $last !~m/^TER/) || ($afl > 1 && $chain ne $oldChain && $last !~m/^TER/)){
			$cnt++;
		}
		$mark[$cnt]=$i;
		$oldRes = $resNr;
		$oldChain = $chain;
		$last = "ATOM";
		$lines[$i]=$_;
		#print "$cnt $i $_";
		$i++;
		$afl++;

	}
}

if($last  !~m/^TER/){
	$nr = $cnt+1;
}
else{
	$nr = $cnt;
}
print "$nr\n";
for($i = 0; $i < @mark; $i++){
	#print "$i $mark[$i]\n";
}
$p = 0;
$rw = open(OUT,">$name\_$p\.pdb");		
if(not defined($rw)) {	
	die "could not open file: $name\_$p\.pdb\n";
}

for($i = 0; $i < @lines; $i++){
	print OUT $lines[$i];
      	if($i == $mark[$p]){
		print OUT "TER\n";
              	close OUT;
              	$p++;
              	if(defined $lines[$i+1]){
			$rw = open(OUT,">$name\_$p\.pdb");	      
              		if(not defined($rw)) {  
        	      		die "could not open file: $name\_$p\.pdb\n";
              		}
		}
	}
	
}
close OUT;
